services:
  - type: web
    name: reno-revenue
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: CY24_PATH
        value: data/CY24.csv
      - key: CY25_PATH
        value: data/CY25.csv
      - key: CY26_PATH
        value: data/CY26.csv
      - key: GSHEET_CSV
        value: https://docs.google.com/spreadsheets/d/e/2PACX-1vSqiJ-d8D6IFLqWoBSwYyDG5-gewEzAob_CvM6CGC-Y8u_VAe_u8YklXn5nzR3DwtJBMNaxJQCf_Zmr/pub?output=csv
